# 项目相关配置
app:
  # 名称
  name: Loupe
  # 版本
  version: 1.0.0
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare: 30

# 日志配置
logging:
  level:
    com.keer.dormitory: debug
    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.cetc15.loupe.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: UUID
      #刷新mapper 调试神器
      refresh-mapper: true
  #原生配置
  configuration:
    # 执行SQL 输出日志
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰下划线转换
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /

file:
  block-path: E:\code\mywork\dormitory\server\file\block\
  student-path: E:\code\mywork\dormitory\server\file\file\

